### PR TITLE
Cleanup and add example

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Don't be too scared of the diff, I mainly moved things into sub files (and improved a bit tests). :D

**Review by Joacchim — CHANGES_REQUESTED** [review]
Looks okay, just one missing LineFeed at the end of src/functions.rs

**Comment by GuillaumeGomez** [comment]
Updated.

**Review by Joacchim — APPROVED** [review]

**Comment by Joacchim** [comment]
Thanks ! :)

**Pull request merged**
